LIBS += $(LIB)

OBJS := \
  $(DIR)abbr0s.o \
  $(DIR)abbr1s.o \
  $(DIR)abbr1a.o \
  $(DIR)abbr0h.o \
  $(DIR)abbr1h.o \
  $(DIR)born.o \
  $(DIR)self_Gen5.o \
  $(DIR)self.o \
  $(DIR)vert.o \
  $(DIR)box.o \
  $(DIR)SquaredME.o

$(LIB): $(LIB)($(OBJS))

$(LIB)($(OBJS)): F-squaredme.d $(DIR)vars.h

