#if 0
* specs.h
* process specifications
* generated by FormCalc 9.7 (27 Jul 2018) on 27-Jul-2018 11:14
#endif

#undef FCVERSION
#define FCVERSION "FormCalc 9.7 (27 Jul 2018)"

#undef PROCNAME
#define PROCNAME "Fb21F21Fb33iF33i"

#undef SQUAREDME_FUNC
#define SQUAREDME_FUNC SquaredME

#undef KIN
#define KIN "2to2.F"

#undef IDENTICALFACTOR
#define IDENTICALFACTOR 1

#undef DIRACFERMIONS
#define DIRACFERMIONS 0

#undef Compose
#define Compose(f,c,A,B,C,D) c(c(c(f(A,1,1),f(B,2,1)),f(C,3,2)),f(D,4,2))

#undef Generic
#define Generic(f,c) Compose(f,c,FERMION,FERMION,FERMION,FERMION)

#undef Anti
#define Anti(f,c) Compose(f,c,-1,1,-1,1)

#undef Mass
#define Mass(f,c) Compose(f,c,ME,ME,MT,MT)

#undef Charge
#define Charge(f,c) Compose(f,c,1,-1,-2/3.D0,2/3.D0)

#undef ColorCharge
#define ColorCharge(f,c) Compose(f,c,0,0,-2/Sqrt(3.D0),2/Sqrt(3.D0))

#undef LeptonNumber
#define LeptonNumber(f,c) Compose(f,c,-1,1,0,0)

