#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.7 (27 Jul 2018) on 27-Jul-2018 11:14
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 4

#include "decl.h"

#else

#include "decl.h"

	ComplexType A0i1, A0i2(3), A0i3(3), A0i4(3), A0i5, A0i6
	ComplexType B0i1(Nbb), B0i2(Nbb), B0i3(Nbb), B0i4(Nbb)
	ComplexType B0i5(Nbb), B0i6(Nbb), B0i7(Nbb,3), B0i8(Nbb,3)
	ComplexType B0i9(Nbb,3), C0i1(Ncc), C0i2(Ncc), C0i3(Ncc)
	ComplexType C0i4(Ncc), C0i5(Ncc), C0i6(Ncc), C0i7(Ncc)
	ComplexType C0i8(Ncc), C0i9(Ncc), C0i10(Ncc), Sub11, Sub20
	ComplexType Sub24, Sub28, Sub29, Sub30, Sub31, Sub32, Sub33
	ComplexType Sub34, Sub35, Sub36, Sub37, Sub38, Sub39, Sub40
	ComplexType Sub41, Sub42, Sub43, Sub44, Sub45, Sub46, Sub47
	ComplexType Sub48, Sub49, Sub51, Sub52, Sub53, Sub54, Sub55
	ComplexType Sub56, Sub57, Sub58, Sub59, Sub60, Sub61, Sub62
	ComplexType Sub63, Sub64, Sub65, Sub66, Sub67, Sub68, Sub69
	ComplexType Sub70, Sub71, Sub72, Sub73, Sub74, Sub75, Sub76
	ComplexType Sub77, Sub78, Sub79, Sub80, Sub81, Sub82, Sub83
	ComplexType Sub89, Sub105, Sub194, Sub195, Sub196, Sub197
	ComplexType Sub198, Sub203, Sub205, Sub332(3), Sub334(3)
	ComplexType Sub335(3), Sub336(3), Sub337(3), Sub338(3)
	ComplexType Sub339(3), Sub340(3), Sub341(3), Sub342(3)
	ComplexType Sub343(3), Sub344(3), Sub345, Sub346, Sub347
	ComplexType Sub351, Sub352, Sub353, Sub355, Sub357, Sub358
	ComplexType Sub362, Sub371, Sub373, Sub375, Sub376, Sub377
	ComplexType Sub379, Sub389, Sub50, Sub333(3)
	common /varXs/ A0i1, A0i2, A0i3, A0i4, A0i5, A0i6, B0i1, B0i2
	common /varXs/ B0i3, B0i4, B0i5, B0i6, B0i7, B0i8, B0i9
	common /varXs/ C0i1, C0i2, C0i3, C0i4, C0i5, C0i6, C0i7
	common /varXs/ C0i8, C0i9, C0i10, Sub11, Sub20, Sub24, Sub28
	common /varXs/ Sub29, Sub30, Sub31, Sub32, Sub33, Sub34
	common /varXs/ Sub35, Sub36, Sub37, Sub38, Sub39, Sub40
	common /varXs/ Sub41, Sub42, Sub43, Sub44, Sub45, Sub46
	common /varXs/ Sub47, Sub48, Sub49, Sub51, Sub52, Sub53
	common /varXs/ Sub54, Sub55, Sub56, Sub57, Sub58, Sub59
	common /varXs/ Sub60, Sub61, Sub62, Sub63, Sub64, Sub65
	common /varXs/ Sub66, Sub67, Sub68, Sub69, Sub70, Sub71
	common /varXs/ Sub72, Sub73, Sub74, Sub75, Sub76, Sub77
	common /varXs/ Sub78, Sub79, Sub80, Sub81, Sub82, Sub83
	common /varXs/ Sub89, Sub105, Sub194, Sub195, Sub196, Sub197
	common /varXs/ Sub198, Sub203, Sub205, Sub332, Sub334
	common /varXs/ Sub335, Sub336, Sub337, Sub338, Sub339
	common /varXs/ Sub340, Sub341, Sub342, Sub343, Sub344
	common /varXs/ Sub345, Sub346, Sub347, Sub351, Sub352
	common /varXs/ Sub353, Sub355, Sub357, Sub358, Sub362
	common /varXs/ Sub371, Sub373, Sub375, Sub376, Sub377
	common /varXs/ Sub379, Sub389, Sub50, Sub333

	ComplexType D0i1(Ndd), D0i2(Ndd), D0i3(Ndd), Sub398, Sub399
	RealType S, T, U
	common /varXa/ D0i1, D0i2, D0i3, Sub398, Sub399, S, T, U

	HelType F1, F2, F3, F4, F5, F6, F7, F8, Sub1, Sub2, Sub3
	HelType F9, F10, F11, F12, F13, F14, F15, F16, F17, F18, Sub4
	HelType Sub5, Sub8, Sub9, Sub12, Sub13, Sub14, Sub15, Sub17
	HelType Sub18, Sub19, Sub21, Sub22, Sub23, Sub25, Sub26
	HelType Sub27, Sub84, Sub85, Sub86, Sub87, Sub88, Sub90
	HelType Sub91, Sub92, Sub93, Sub94, Sub95, Sub96, Sub97
	HelType Sub98, Sub99, Sub100, Sub101, Sub102, Sub103, Sub104
	HelType Sub106, Sub107, Sub108, Sub109, Sub110, Sub111
	HelType Sub112, Sub113, Sub114, Sub115, Sub116, Sub117
	HelType Sub118, Sub119, Sub120, Sub121, Sub122, Sub123
	HelType Sub124, Sub125, Sub126, Sub127, Sub128, Sub129
	HelType Sub130, Sub131, Sub132, Sub133, Sub134, Sub135
	HelType Sub136, Sub137, Sub138, Sub139, Sub140, Sub141
	HelType Sub142, Sub143, Sub144, Sub145, Sub146, Sub147
	HelType Sub148, Sub149, Sub150, Sub151, Sub152, Sub153
	HelType Sub154, Sub155, Sub156, Sub157, Sub158, Sub159
	HelType Sub160, Sub161, Sub162, Sub163, Sub164, Sub165
	HelType Sub166, Sub167, Sub168, Sub169, Sub170, Sub171
	HelType Sub172, Sub173, Sub174, Sub175, Sub176, Sub177
	HelType Sub178, Sub179, Sub180, Sub181, Sub182, Sub183
	HelType Sub184, Sub185, Sub186, Sub187, Sub188, Sub189
	HelType Sub190, Sub191, Sub192, Sub193, Sub199, Sub200
	HelType Sub201, Sub202, Sub204, Sub206, Sub207, Sub208
	HelType Sub209, Sub210, Sub211, Sub212, Sub213, Sub214
	HelType Sub215, Sub216, Sub217, Sub218, Sub219, Sub220
	HelType Sub221, Sub222, Sub223, Sub224, Sub225, Sub226
	HelType Sub228, Sub229, Sub231, Sub232, Sub233, Sub234
	HelType Sub235, Sub236, Sub237, Sub238, Sub239, Sub240
	HelType Sub241, Sub242, Sub243, Sub244, Sub245, Sub246
	HelType Sub247, Sub248, Sub250, Sub251, Sub252, Sub253
	HelType Sub254, Sub255, Sub257, Sub258, Sub259, Sub260
	HelType Sub261, Sub262, Sub263, Sub264, Sub265, Sub266
	HelType Sub267, Sub268, Sub269, Sub270, Sub271, Sub272
	HelType Sub273, Sub274, Sub275, Sub276, Sub277, Sub278
	HelType Sub279, Sub280, Sub281, Sub282, Sub283, Sub284
	HelType Sub285, Sub286, Sub287, Sub288, Sub290, Sub291
	HelType Sub292, Sub293, Sub294, Sub295, Sub296, Sub297
	HelType Sub298, Sub299, Sub300, Sub301, Sub302, Sub303
	HelType Sub304, Sub305, Sub306, Sub307, Sub308, Sub309
	HelType Sub310, Sub311, Sub312, Sub313, Sub314, Sub315
	HelType Sub316, Sub317, Sub318, Sub319, Sub320, Sub321
	HelType Sub322, Sub323, Sub324, Sub325, Sub326, Sub327
	HelType Sub328, Sub329, Sub330, Sub331, Sub354, Sub356
	HelType Sub359, Sub360, Sub361, Sub363, Sub364, Sub365
	HelType Sub366, Sub367, Sub368, Sub369, Sub370, Sub372
	HelType Sub374, Sub378, Sub380, Sub381, Sub382, Sub383
	HelType Sub384, Sub385, Sub386, Sub387, Sub388, Sub390
	HelType Sub391, Sub392, Sub393, Sub394, Sub397, Sub400
	HelType Sub401, Sub7, Sub10, Sub227, Sub230, Sub249, Sub289
	HelType Sub348, Sub349, Sub350, Sub395, Sub396
	common /varXh/ F1, F2, F3, F4, F5, F6, F7, F8, Sub1, Sub2
	common /varXh/ Sub3, F9, F10, F11, F12, F13, F14, F15, F16
	common /varXh/ F17, F18, Sub4, Sub5, Sub8, Sub9, Sub12
	common /varXh/ Sub13, Sub14, Sub15, Sub17, Sub18, Sub19
	common /varXh/ Sub21, Sub22, Sub23, Sub25, Sub26, Sub27
	common /varXh/ Sub84, Sub85, Sub86, Sub87, Sub88, Sub90
	common /varXh/ Sub91, Sub92, Sub93, Sub94, Sub95, Sub96
	common /varXh/ Sub97, Sub98, Sub99, Sub100, Sub101, Sub102
	common /varXh/ Sub103, Sub104, Sub106, Sub107, Sub108
	common /varXh/ Sub109, Sub110, Sub111, Sub112, Sub113
	common /varXh/ Sub114, Sub115, Sub116, Sub117, Sub118
	common /varXh/ Sub119, Sub120, Sub121, Sub122, Sub123
	common /varXh/ Sub124, Sub125, Sub126, Sub127, Sub128
	common /varXh/ Sub129, Sub130, Sub131, Sub132, Sub133
	common /varXh/ Sub134, Sub135, Sub136, Sub137, Sub138
	common /varXh/ Sub139, Sub140, Sub141, Sub142, Sub143
	common /varXh/ Sub144, Sub145, Sub146, Sub147, Sub148
	common /varXh/ Sub149, Sub150, Sub151, Sub152, Sub153
	common /varXh/ Sub154, Sub155, Sub156, Sub157, Sub158
	common /varXh/ Sub159, Sub160, Sub161, Sub162, Sub163
	common /varXh/ Sub164, Sub165, Sub166, Sub167, Sub168
	common /varXh/ Sub169, Sub170, Sub171, Sub172, Sub173
	common /varXh/ Sub174, Sub175, Sub176, Sub177, Sub178
	common /varXh/ Sub179, Sub180, Sub181, Sub182, Sub183
	common /varXh/ Sub184, Sub185, Sub186, Sub187, Sub188
	common /varXh/ Sub189, Sub190, Sub191, Sub192, Sub193
	common /varXh/ Sub199, Sub200, Sub201, Sub202, Sub204
	common /varXh/ Sub206, Sub207, Sub208, Sub209, Sub210
	common /varXh/ Sub211, Sub212, Sub213, Sub214, Sub215
	common /varXh/ Sub216, Sub217, Sub218, Sub219, Sub220
	common /varXh/ Sub221, Sub222, Sub223, Sub224, Sub225
	common /varXh/ Sub226, Sub228, Sub229, Sub231, Sub232
	common /varXh/ Sub233, Sub234, Sub235, Sub236, Sub237
	common /varXh/ Sub238, Sub239, Sub240, Sub241, Sub242
	common /varXh/ Sub243, Sub244, Sub245, Sub246, Sub247
	common /varXh/ Sub248, Sub250, Sub251, Sub252, Sub253
	common /varXh/ Sub254, Sub255, Sub257, Sub258, Sub259
	common /varXh/ Sub260, Sub261, Sub262, Sub263, Sub264
	common /varXh/ Sub265, Sub266, Sub267, Sub268, Sub269
	common /varXh/ Sub270, Sub271, Sub272, Sub273, Sub274
	common /varXh/ Sub275, Sub276, Sub277, Sub278, Sub279
	common /varXh/ Sub280, Sub281, Sub282, Sub283, Sub284
	common /varXh/ Sub285, Sub286, Sub287, Sub288, Sub290
	common /varXh/ Sub291, Sub292, Sub293, Sub294, Sub295
	common /varXh/ Sub296, Sub297, Sub298, Sub299, Sub300
	common /varXh/ Sub301, Sub302, Sub303, Sub304, Sub305
	common /varXh/ Sub306, Sub307, Sub308, Sub309, Sub310
	common /varXh/ Sub311, Sub312, Sub313, Sub314, Sub315
	common /varXh/ Sub316, Sub317, Sub318, Sub319, Sub320
	common /varXh/ Sub321, Sub322, Sub323, Sub324, Sub325
	common /varXh/ Sub326, Sub327, Sub328, Sub329, Sub330
	common /varXh/ Sub331, Sub354, Sub356, Sub359, Sub360
	common /varXh/ Sub361, Sub363, Sub364, Sub365, Sub366
	common /varXh/ Sub367, Sub368, Sub369, Sub370, Sub372
	common /varXh/ Sub374, Sub378, Sub380, Sub381, Sub382
	common /varXh/ Sub383, Sub384, Sub385, Sub386, Sub387
	common /varXh/ Sub388, Sub390, Sub391, Sub392, Sub393
	common /varXh/ Sub394, Sub397, Sub400, Sub401, Sub7, Sub10
	common /varXh/ Sub227, Sub230, Sub249, Sub289, Sub348
	common /varXh/ Sub349, Sub350, Sub395, Sub396

	integer Gen5
	common /indices/ Gen5

	HelType Ctree(HelDim(1)), Cloop(HelDim(1))
	ComplexType MatSUN(1,1)
	common /formfactors/ Ctree, Cloop, MatSUN

#endif

