#if 0
* RenConst.h.c
* RC declarations
* generated by FormCalc 9.7 (27 Jul 2018) on 27-Jul-2018 11:15
#endif

#ifndef RenConst_h
#define RenConst_h

struct varRenConst {
  ComplexType dMWsq1, dMZsq1, dSW1, dZAA1, dZAZ1, dZe1, dZZA1;
  ComplexType dZZZ1, dZfL1[3][3][3], dZfR1[3][3][3];
} varRenConst_;

#define dMWsq1 varRenConst_.dMWsq1
#define dMZsq1 varRenConst_.dMZsq1
#define dSW1 varRenConst_.dSW1
#define dZAA1 varRenConst_.dZAA1
#define dZAZ1 varRenConst_.dZAZ1
#define dZe1 varRenConst_.dZe1
#define dZZA1 varRenConst_.dZZA1
#define dZZZ1 varRenConst_.dZZZ1
#define dZfL1(i,j,k) varRenConst_.dZfL1[k-1][j-1][i-1]
#define dZfR1(i,j,k) varRenConst_.dZfR1[k-1][j-1][i-1]

#else

#endif

